version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/HsReplayBot
    image: library/golang:onbuild
    volumes:
      - .:/go/src/github.com/HsReplayBot
    tty: true
    command: tail -f /dev/null
    links:
      - redis
      - mysql
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'hs_replay_bot'
        MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: